In [1]:
from mxnet import nd

In [3]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [6]:
x.shape

(12,)

In [7]:
x.size

12

In [8]:
x.sigmoid

<bound method NDArray.sigmoid of 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>>

In [9]:
help(x.sigmoid)

Help on method sigmoid in module mxnet.ndarray.ndarray:

sigmoid(*args, **kwargs) method of mxnet.ndarray.ndarray.NDArray instance
    Convenience fluent method for :py:func:`sigmoid`.
    
    The arguments are the same as for :py:func:`sigmoid`, with
    this array as data.



In [10]:
x1 = x.reshape(3,4)
x1


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
x2 = x.reshape(4,4)
x2

MXNetError: [17:01:54] C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc:212: Check failed: shape_.Size() >= shape.Size() (12 vs. 16) NDArray.Reshape: target shape size is larger current shape

In [13]:
x2 = x.reshape(4,-1)
x2


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>

In [14]:
x3 = x.reshape(-1,2)
x3


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
<NDArray 6x2 @cpu(0)>

In [16]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [17]:
nd.ones((2,3))


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [18]:
nd.random.normal(0,1,shape=(2,6))


[[ 1.1630785   0.4838046   0.29956347  0.15302546 -1.1688148   1.558071  ]
 [-0.5459446  -2.3556297   0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 2x6 @cpu(0)>

## 运算

In [20]:
y3=nd.array([[1,2]])
y3


[[1. 2.]]
<NDArray 1x2 @cpu(0)>

In [21]:
x3


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
<NDArray 6x2 @cpu(0)>

In [22]:
x3+y3


[[ 1.  3.]
 [ 3.  5.]
 [ 5.  7.]
 [ 7.  9.]
 [ 9. 11.]
 [11. 13.]]
<NDArray 6x2 @cpu(0)>

In [23]:
x3*y3


[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]
 [ 8. 18.]
 [10. 22.]]
<NDArray 6x2 @cpu(0)>

In [24]:
x3/y3


[[ 0.   0.5]
 [ 2.   1.5]
 [ 4.   2.5]
 [ 6.   3.5]
 [ 8.   4.5]
 [10.   5.5]]
<NDArray 6x2 @cpu(0)>

In [25]:
y3.exp()


[[2.7182817 7.389056 ]]
<NDArray 1x2 @cpu(0)>

In [26]:
y3.T


[[1.]
 [2.]]
<NDArray 2x1 @cpu(0)>

In [27]:
nd.dot(x3,y3.T)


[[ 2.]
 [ 8.]
 [14.]
 [20.]
 [26.]
 [32.]]
<NDArray 6x1 @cpu(0)>

In [28]:
y3 == x3


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
<NDArray 6x2 @cpu(0)>

In [2]:
x = nd.array([[1,2,3],[4,5,6],[7,8,9]])
x


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [3]:
x.sum()


[45.]
<NDArray 1 @cpu(0)>

In [4]:
x.sum().asscalar()

45.0

In [10]:
y = nd.array([[1,2,3]])
y


[[1. 2. 3.]]
<NDArray 1x3 @cpu(0)>

In [11]:
x+y


[[ 2.  4.  6.]
 [ 5.  7.  9.]
 [ 8. 10. 12.]]
<NDArray 3x3 @cpu(0)>

In [12]:
x+y.T


[[ 2.  3.  4.]
 [ 6.  7.  8.]
 [10. 11. 12.]]
<NDArray 3x3 @cpu(0)>

In [13]:
y.T


[[1.]
 [2.]
 [3.]]
<NDArray 3x1 @cpu(0)>

In [16]:
y + 1


[[2. 3. 4.]]
<NDArray 1x3 @cpu(0)>

In [17]:
y.reshape((2,2))

MXNetError: [13:51:35] C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc:212: Check failed: shape_.Size() >= shape.Size() (3 vs. 4) NDArray.Reshape: target shape size is larger current shape

In [25]:
t=nd.array([[0]])
t


[[0.]]
<NDArray 1x1 @cpu(0)>

In [27]:
nd.concat(y,t,dim=1)


[[1. 2. 3. 0.]]
<NDArray 1x4 @cpu(0)>

In [28]:
nd.concat(y,nd.array([[4]]),dim=1)


[[1. 2. 3. 4.]]
<NDArray 1x4 @cpu(0)>

In [29]:
t=nd.concat(y,nd.array([[4]]),dim=1)

In [30]:
t.reshape((2,2))
t


[[1. 2. 3. 4.]]
<NDArray 1x4 @cpu(0)>

In [31]:
t=nd.array([[1,2],[3,0]])
t


[[1. 2.]
 [3. 0.]]
<NDArray 2x2 @cpu(0)>

In [32]:
x


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [33]:
x + t

MXNetError: [14:00:20] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./elemwise_binary_broadcast_op.h:68: Check failed: l == 1 || r == 1 operands could not be broadcast together with shapes [3,3] [2,2]

In [34]:
t=nd.array([1,2,3,0])
t


[1. 2. 3. 0.]
<NDArray 4 @cpu(0)>

In [35]:
x


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [36]:
x + t

MXNetError: [14:00:57] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./elemwise_binary_broadcast_op.h:68: Check failed: l == 1 || r == 1 operands could not be broadcast together with shapes [3,3] [4]

In [37]:
x


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [38]:
x[2,2]


[9.]
<NDArray 1 @cpu(0)>

In [39]:
x[1,:]=0
x


[[1. 2. 3.]
 [0. 0. 0.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [40]:
id(x)

1836145456576

In [41]:
hex(id(x))

'0x1ab82cc35c0'

In [42]:
import numpy as np

In [43]:
np.ones(3)

array([1., 1., 1.])

In [45]:
x = np.ones((3,2))
y = nd.array(x)
y


[[1. 1.]
 [1. 1.]
 [1. 1.]]
<NDArray 3x2 @cpu(0)>

In [47]:
y.asnumpy()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [49]:
nd.zeros((3,2)) < nd.ones((3,2))


[[1. 1.]
 [1. 1.]
 [1. 1.]]
<NDArray 3x2 @cpu(0)>

## 2.3 自动求导

In [50]:
x=nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [51]:
x.attach_grad()

In [52]:
help(x.attach_grad)

Help on method attach_grad in module mxnet.ndarray.ndarray:

attach_grad(grad_req='write', stype=None) method of mxnet.ndarray.ndarray.NDArray instance
    Attach a gradient buffer to this NDArray, so that `backward`
    can compute gradient with respect to it.
    
    Parameters
    ----------
    grad_req : {'write', 'add', 'null'}
        How gradient will be accumulated.
        - 'write': gradient will be overwritten on every backward.
        - 'add': gradient will be added to existing value on every backward.
        - 'null': do not compute gradient for this NDArray.
    stype : str, optional
        The storage type of the gradient array. Defaults to the same stype of this NDArray.



In [54]:
from mxnet import autograd

In [58]:
with autograd.record():
    y = nd.dot(x.T,x)
    print(y,type(y)) 
    y.backward()
    print(x,x.grad)## 1. 不加print是打印不出来的，2. 真的==2x的值


[[14.]]
<NDArray 1x1 @cpu(0)> <class 'mxnet.ndarray.ndarray.NDArray'>

[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)> 
[[0.]
 [2.]
 [4.]
 [6.]]
<NDArray 4x1 @cpu(0)>


In [59]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [62]:
x.norm()


[3.7416573]
<NDArray 1 @cpu(0)>

In [61]:
help(x.norm)

Help on method norm in module mxnet.ndarray.ndarray:

norm(*args, **kwargs) method of mxnet.ndarray.ndarray.NDArray instance
    Convenience fluent method for :py:func:`norm`.
    
    The arguments are the same as for :py:func:`norm`, with
    this array as data.



In [64]:
x.norm().asscalar()

3.7416573

In [71]:
t = nd.array([[1,1,1]])
t.norm()


[1.7320508]
<NDArray 1 @cpu(0)>